FROM amazonlinux:2
ENV container docker
LABEL __copyright__="(C) Dayspring Technologies Inc." \
      __version__="1.0.0"

# Perform a package update
RUN amazon-linux-extras enable php7.4
RUN yum -y update

# Add some familiar utilities
RUN yum -y install procps \
  htop \
  grep \
  findutils \
  iputils \
  iproute \
  wget \
  git \
  ruby \
  libxcrypt-compat

# Add sshd server so we can 'vagrant ssh' later
RUN yum -y install openssh-server openssh-clients passwd sudo; 
RUN mkdir /var/run/sshd
RUN ssh-keygen -t rsa -f /etc/ssh/ssh_host_rsa_key -N ''
RUN useradd --create-home -s /bin/bash vagrant
RUN echo -e "vagrant\nvagrant" | (passwd --stdin vagrant)
RUN echo 'vagrant ALL=(ALL) NOPASSWD: ALL' > /etc/sudoers.d/vagrant
RUN chmod 440 /etc/sudoers.d/vagrant
RUN mkdir -p /home/vagrant/.ssh
RUN chmod 700 /home/vagrant/.ssh
ADD https://raw.githubusercontent.com/hashicorp/vagrant/master/keys/vagrant.pub /home/vagrant/.ssh/authorized_keys
RUN chmod 600 /home/vagrant/.ssh/authorized_keys
RUN chown -R vagrant:vagrant /home/vagrant/.ssh

# Allow public key authentication for 'vagrant ssh'
RUN sed -i 's/^#PubkeyAuthentication yes/PubkeyAuthentication yes/i' /etc/ssh/sshd_config

# As the container isn't normally running systemd, /run/nologin needs to be removed to allow SSH
RUN rm -rf /run/nologin

# Install the replacement systemctl command
RUN yum -y install python3
COPY vagrant/files/docker/systemctl3.py /usr/bin/systemctl
RUN chmod 755 /usr/bin/systemctl

# Tools specific to our normal environment
RUN yum -y install php \
  php-intl \
  php-soap \ 
  php-mysqlnd \
  php-zipstream \
  httpd 

# Setup of httpd
RUN rm -rf /etc/httpd/
# Copy http config files as generated by chef on virtualbox
COPY files/etc/httpd/ /etc/httpd/
RUN systemctl enable httpd

RUN mkdir -p /etc/cron.d

CMD /usr/bin/systemctl
